config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "/search", to: "pages#search", as: "search_results"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :use_cases, only: [:index, :show]
  resources :articles, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/python.rb
class Python < ApplicationRecord
  has_many :use_cases
end

app/models/ruby.rb
class Ruby < ApplicationRecord
  has_many :use_cases
end

app/models/use_case.rb
class UseCase < ApplicationRecord
  belongs_to :python
  belongs_to :ruby
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description_and_category,
    against: [ :title, :description, :category ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @populars = UseCase.where(popular: true)
  end

  def search
    @query = params[:query]
    @use_cases = UseCase.search_by_title_and_description_and_category(@query).paginate(page: params[:page], per_page: 5)
    @use_cases_total = UseCase.search_by_title_and_description_and_category(@query).size
  end
end

app/controllers/use_cases_controller.rb
class UseCasesController < ApplicationController
  def index
    @use_cases_total = UseCase.all
    @use_cases = UseCase.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def show
    @use_case = UseCase.find(params[:id])
    @use_case_total = UseCase.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'navbar__link--link--active' if request.path == test_path
    ''
  end
end

app/views/articles/index.html.erb
<div class="container">
  <div class="index-use">
    <div class="index-use__header">
      <h1>Articles on Ruby & Python</h1>
    </div>
    <% @articles.each do |article| %>
      <div class="card-product-article my-5 p-5">
        <div class="card-product-article__content">
          <h2><%= article.title %></h2>
          <p><%= article.description[0, 139] %>...</p>
          <p class="card-product-article__content--name">By <%= article.author %> (<%= article.time_length %>)</p>
          <div class="card-product-article__btn w-25 mt-3">
            <a target="_blank" href="<%= article.url %>">Read more</a>
          </div>
        </div>
        <div class = "card-product-article--publish-btn m-3">
          <div>
            <p class="card-product-article__content--name border p-1 my-3"><%= article.category %></p>
            <p class="card-product-article__content--name mt-4">Published <%= article.date %></p>
          </div>
        </div>
        <div class="card-product-article__img">
          <img class="avatar" src="<%= article.image_url %>" alt="avatar">
        </div>
      </div>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @use_cases, :container => false %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Py2rb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "partials/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "partials/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="home">
    <div class="mb-5">
      <div class="home__header">
        <h1 class="my-4">
            <span id="banner-typed-text"></span>
        </h1>
        <h3>Find up to date snippets for translating Ruby to Python.</h3>
      </div>
      <div class="home__search">
        <%= form_tag search_results_path, class: "d-flex", method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find some code"
          %>
          <%= submit_tag "Search", class: "btn btn-success ml-2" %>
        <% end %>
      </div>
    </div>
    <hr class="shadow-sm">
    <div class="container my-5">
      <div class="d-flex justify-content-center align-items-center">
        <h3>Popular code cases</h3>
      </div>
      <% @populars.each do |caser| %>
        <div class="card card-home-container my-5">
          <div class="card__title py-2">
            <h1><%= caser.title %></h1>
          </div>
          <div class="card__sub-info py-2">
            <div class="card__sub-info--category">
              <%= caser.category.upcase %>
            </div>
            <div class="card__sub-info--update">
              <p>Last updated <%= caser.updated_at.strftime('%a, %e %b %y') %></p>
            </div>
          </div>
          <div class="card__description py-2">
            <p>
              <%= caser.description %>
            </p>
          </div>
          <div class="card__snippet py-2">
            <pre class="ruby-style">
              <% caser.ruby.code.each do |rb| %>
                <%= sanitize rb %>
              <% end %>
              <p class="card__snippet--code--def">Ruby</p>
            </pre>
          </div>
          <div class="card__snippet py-2">
            <pre class="python-style">
              <% caser.python.code.each do |py| %>
                <%= sanitize py %>
              <% end %>
              <p class="card__snippet--code--def">Python</p>
            </pre>
          </div>
          <div class="card__output">
            <div class="card__output--code">
              <code class="text-primary">
                <%= caser.output %>
              </code>
              <p class="card__output--code--def">Output</p>
            </div>
          </div>
          <div class="card__buttons my-4">
            <a class="card__buttons--btn card__buttons--btn--green m-2 w-50" target="_blank" href="<%= caser.ruby.documentation_url %>">Ruby: Learn More</a>
            <a class="card__buttons--btn card__buttons--btn--green m-2 w-50" target="_blank" href="<%= caser.python.documentation_url %>">Python: Learn More</a>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "See more", use_cases_path, class: "btn btn-success w-50" %>
    </div>
  </div>
</div>

app/views/pages/search.html.erb
<div class="container">
  <div class="index-use">
    <div class="index-use__header">
      <h1>Search results for <%= @query %></h1>
      <p>Code cases found (<%= @use_cases_total %>)</p>
    </div>
    <% @use_cases.each do |caser| %>
      <%= link_to use_case_path(caser) do %>
        <div class="card-product my-3">
          <div class="card-product-infos">
            <h2><%= caser.title %></h2>
            <p><%= caser.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @use_cases, :container => false %>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This website was designed by Damon Roberts, DRS ©
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar d-flex align-items-center justify-content-between py-3">
  <div class="navbar__links">
    <a href="/"><%= image_tag asset_path('logo.png'), class: "mr-2 logo" %></a>
    <a href="/" class="mr-2 navbar__link--link m-2 <%= current_class?(root_path) %>">Home</a>
    <a href="/use_cases" class="mr-2 navbar__link--link m-2 <%= current_class?(use_cases_path) %>">Code</a>
    <a href="/articles" class="mr-2 navbar__link--link m-2 <%= current_class?(articles_path) %>">Articles</a>
  </div>
  <div class="d-flex align-items-center">
    <%= form_tag search_results_path, class: "d-flex", method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find some code"
      %>
      <%= submit_tag "Search", class: "btn btn-success ml-2" %>
    <% end %>
    <i class="moon-icon fas fa-moon fa-2x ml-5"></i>
  </div>
</div>

app/views/use_cases/index.html.erb
<div class="container">
  <div class="index-use">
    <div class="index-use__header">
      <h1>All code.</h1>
      <p>Code cases (<%= @use_cases_total.size %>)</p>
    </div>
    <% @use_cases.each do |caser| %>
      <%= link_to use_case_path(caser) do %>
        <div class="card-product my-3">
          <div class="card-product-infos">
            <h2><%= caser.title %></h2>
            <p><%= caser.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @use_cases, :container => false %>
    </div>
  </div>
</div>

app/views/use_cases/show.html.erb
<div class="card-page-container">
  <div class="card card-container">
    <div class="m-5">
      <% if (@use_case.id) - 1 > 0 %>
        <%= link_to use_case_path(@use_case.id - 1) do %>
          <i class="fas fa-chevron-left fa-3x card__icon"></i>
        <% end %>
      <% else %>
        <%= link_to use_case_path(@use_case_total.size) do %>
          <i class="fas fa-chevron-left fa-3x card__icon"></i>
        <% end %>
      <% end %>
    </div>
    <div class="card-content">
      <div class="card__title py-2">
        <h1><%= @use_case.title %></h1>
      </div>
      <div class="card__sub-info py-2">
        <div class="card__sub-info--category">
          <%= @use_case.category.upcase %>
        </div>
        <div class="card__sub-info--update">
          <p>Last updated <%= @use_case.updated_at.strftime('%a, %e %b %y') %></p>
        </div>
      </div>
      <div class="card__description py-2">
        <p>
          <%= @use_case.description %>
        </p>
      </div>
      <div class="card__snippet py-2">
        <pre class="ruby-style">
          <% @use_case.ruby.code.each do |rb| %>
            <%= sanitize rb %>
          <% end %>
          <p class="card__snippet--code--def">Ruby</p>
        </pre>
      </div>
      <div class="card__snippet py-2">
        <pre class="python-style">
          <% @use_case.python.code.each do |py| %>
            <%= sanitize py %>
          <% end %>
          <p class="card__snippet--code--def">Python</p>
        </pre>
      </div>
      <div class="card__output">
        <div class="card__output--code">
          <code class="text-primary">
            <%= @use_case.output %>
          </code>
          <p class="card__output--code--def">Output</p>
        </div>
      </div>
      <div class="card__buttons my-4">
        <a class="card__buttons--btn card__buttons--btn--green m-2 w-50" target="_blank" href="<%= @use_case.ruby.documentation_url %>">Ruby: Learn More</a>
        <a class="card__buttons--btn card__buttons--btn--green m-2 w-50" target="_blank" href="<%= @use_case.python.documentation_url %>">Python: Learn More</a>
      </div>
    </div>
    <div class="m-5">
      <% if (@use_case.id + 1) > @use_case_total.size %>
        <%= link_to use_case_path(1) do %>
          <i class="fas fa-chevron-right fa-3x card__icon"></i>
        <% end %>
      <% else %>
        <%= link_to use_case_path(@use_case.id + 1) do %>
          <i class="fas fa-chevron-right fa-3x card__icon"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>